services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    command: ["npm", "run", "start:prod"]
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
